"""adicionando tabela pizza

Revision ID: 62b72f096946
Revises: 
Create Date: 2024-11-12 12:54:17.952674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b72f096946'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(length=280), nullable=True),
    sa.Column('imagem', sa.String(length=280), nullable=True),
    sa.Column('ingredientes', sa.String(length=280), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza')
    # ### end Alembic commands ###
